#!/usr/bin/env ruby
# based on http://mpov.timmorgan.org/super-simple-clipboard-history-for-linux/

STORE="#{ENV['HOME']}/.clipboard-history"
LIMIT=100
DMENU_COMMAND='dmenu -nb "#fffffa" -nf "#111111" -sb "#dadada" -sf "#111111" -fn "Triplicate T3c" -l 100'

unless File.exist?(STORE)
  File.open(STORE, 'w') { |f| f.write('') }
end

#puts 'read clips'
clips = File.read(STORE).split(/\n/).map { |c| eval(c) }

if ARGV[0] == 'menu'
#  puts 'show menu'
  if sel = eval(`cat #{STORE} | #{DMENU_COMMAND} `)
    IO.popen('xclip -i -selection clipboard', 'w') { |f| f.write(sel) }
  end
else
  loop do
    clip = `xclip -o -selection clipboard`
    if clip != clips.first
      #puts 'add clip'
      clips = ([clip] + clips).uniq[0...LIMIT]
      File.open(STORE, 'w') do |file|
        file.write(clips.map { |c| "#{c.inspect}\n" }.join())
      end
    end
    sleep 1
  end
end
